version: '3.8'
services:
  bitcoind:
    container_name: bitcoind
    user: 1000:1000
    image: lncm/bitcoind:v25.0
    logging:
      options:
        max-size: 50m
    restart: on-failure
    stop_grace_period: 15m30s
    volumes:
      - ./bitcoin:/data/.bitcoin

  tor:
    container_name: tor
    user: 1000:1000
    build:
      dockerfile: Dockerfile.tor
      context: .
    networks:
      - btc
    restart: on-failure
    expose:
      - 9050
    ports:
      - "9050:9050"

  electrs:
    cointainer_name: electrs
    user: 1000:1000
    build:
      dockerfile: Dockerfile.electrs
      context: .
    restart: on-failure
    volumes:
      - ./bitcoin:/data/.bitcoin
      - ./electrs:/data/.electrs
      - ./electrs/electrs.local.toml:/etc/electrs/config.toml:ro

networks:
  btc:
    driver: bridge
    ipam:
      config:
        # keep aligned with bitcoin.template.conf and bitcoin.conf
        - subnet: 172.31.0.0/24
          gateway: 172.31.0.1
