version: '3.8'
services:
  tailscaled:
    container_name: tailscaled
    hostname: tailscaled
    user: 1000:1000
    image: tailscale/tailscale:v1.68.1
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_USERSPACE=TRUE
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale/btc/var/lib:/var/lib
    networks:
      - btc

  bitcoind:
    depends_on:
      tailscaled:
        condition: service_started
    network_mode: "service:tailscaled"

  electrs:
    depends_on:
      tailscaled:
        condition: service_started
      bitcoind:
        condition: service_started
    network_mode: "service:tailscaled"
    volumes:
      - ./bitcoin:/data/.bitcoin
      - ./electrs:/data/.electrs
      - ./electrs/electrs.vpn.toml:/etc/electrs/config.toml:ro

  tor:
    volumes:
      # no tor hidden service
      - ./tor/torrc.local:/etc/tor/torrc:ro
