version: '3.8'
services:
  bitcoind:
    container_name: bitcoind
    user: 1000:1000
    image: lncm/bitcoind:v25.0
    networks:
      - btc
    logging:
      options:
        max-size: 50m
    restart: on-failure
    stop_grace_period: 15m30s
    ports:
      - "127.0.0.1:8332:8332" # only local publication, use in conjuction with ssh tunnel
    volumes:
      - ./bitcoin:/data/.bitcoin

  tor:
    container_name: tor
    user: "1000:1000"
    build:
      dockerfile: Dockerfile.tor
      context: .
    networks:
      - btc
    restart: on-failure
    volumes:
      - ./tor/torrc:/etc/tor/torrc:ro
      - ./tor/bitcoin_hidden/:/var/lib/tor/bitcoin_hidden/
    expose:
      - 9050
    ports:
      - "9050:9050"

networks:
  btc:
    driver: bridge
    ipam:
      config:
        # keep aligned with bitcoin.template.conf and bitcoin.conf
        - subnet: 172.31.0.0/24
          gateway: 172.31.0.1
