version: '3.8'
services:
  bitcoind:
    networks:
      - btc
    ports:
      - "127.0.0.1:8332:8332" # only local publication, use in conjunction with ssh tunnel

  electrs:
    depends_on:
      bitcoind:
        condition: service_started
    networks:
      - btc
    ports:
      - "127.0.0.1:50001:50001" # only local publication, use in conjunction with ssh tunnel
