version: '3.8'
services:
  bitcoind:
    networks:
      - btc

  electrs:
    depends_on:
      tailscaled:
        condition: service_started
      bitcoind:
        condition: service_started
    networks:
      - btc

  tor:
    volumes:
      - ./tor/torrc.tor:/etc/tor/torrc:ro
      - ./tor/bitcoin_hidden/:/var/lib/tor/bitcoin_hidden/
