version: '3.8'
services:
  host-tailscale:
    container_name: node.remote
    hostname: node.remote
    image: tailscale/tailscale:stable
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_USERSPACE=TRUE
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale/host/var/lib:/var/lib
    cap_add: # Required for tailscale to work
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    network_mode: host
