network = "bitcoin"
daemon_dir= "/data/.bitcoin"
daemon_rpc_addr = "tailscaled:8332"
daemon_p2p_addr = "tailscaled:8333"

electrum_rpc_addr = "127.0.0.1:50001"
db_dir = "/data/.electrs/db"
index_lookup_limit = 1000

log_filters = "INFO"
timestamp = true
